#!/usr/bin/env bash

IGNORE_PKGS="(vendor)"
TESTS=`find . -name \*_test.go | while read a; do dirname $a; done | sort | uniq | egrep -v "$IGNORE_PKGS"`

<<COMMENT
IGNORE_PKGS="(vendor)"
TESTS=`find . -name \*_test.go | while read a; do dirname $a; done | sort | uniq | egrep -v "$IGNORE_PKGS"`
go vet $TESTS

vetShadowRes=$( go tool vet -shadow $TESTS 2>&1 >/dev/null )
echo $vetShadowRes
COMMENT

echo "Checking gofmt..."
fmtRes=$(gofmt -l -s $TESTS 2>&1 >/dev/null)
if [ -n "${fmtRes}" ]; then
	echo -e "gofmt checking failed:\n${fmtRes}"
	exit 255
fi

echo "Checking go vet..."
vetRes=$(go vet $TESTS 2>&1 >/dev/null)
if [ -n "${vetRes}" ]; then
	echo -e "go vet checking failed:\n${vetRes}"
	exit 255
fi

echo "Checking go tool vet -shadow..."
vetShadowRes=$(go tool vet -shadow $TESTS 2>&1 >/dev/null)
if [ -n "${vetShadowRes}" ]; then
	echo -e "go vet shadow checking failed:\n${vetShadowRes}"
	exit 255
fi

echo "Running tests...";
go test -v -cover -cpu 1,2,4 $TESTS;
go test -v -cover -cpu 1,2,4 -race $TESTS;
