// Code generated by protoc-gen-gogo.
// source: raft/raftpb/message.proto
// DO NOT EDIT!

package raftpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// (etcd raft.raftpb.Message)
type Message struct {
	Type                           MESSAGE_TYPE `protobuf:"varint,1,opt,name=Type,proto3,enum=raftpb.MESSAGE_TYPE" json:"Type,omitempty"`
	From                           uint64       `protobuf:"varint,2,opt,name=From,proto3" json:"From,omitempty"`
	To                             uint64       `protobuf:"varint,3,opt,name=To,proto3" json:"To,omitempty"`
	SenderCurrentCommittedIndex    uint64       `protobuf:"varint,4,opt,name=SenderCurrentCommittedIndex,proto3" json:"SenderCurrentCommittedIndex,omitempty"`
	SenderCurrentTerm              uint64       `protobuf:"varint,5,opt,name=SenderCurrentTerm,proto3" json:"SenderCurrentTerm,omitempty"`
	LogIndex                       uint64       `protobuf:"varint,6,opt,name=LogIndex,proto3" json:"LogIndex,omitempty"`
	LogTerm                        uint64       `protobuf:"varint,7,opt,name=LogTerm,proto3" json:"LogTerm,omitempty"`
	Entries                        []Entry      `protobuf:"bytes,8,rep,name=Entries" json:"Entries"`
	Snapshot                       Snapshot     `protobuf:"bytes,9,opt,name=Snapshot" json:"Snapshot"`
	Reject                         bool         `protobuf:"varint,10,opt,name=Reject,proto3" json:"Reject,omitempty"`
	RejectHintFollowerLogLastIndex uint64       `protobuf:"varint,11,opt,name=RejectHintFollowerLogLastIndex,proto3" json:"RejectHintFollowerLogLastIndex,omitempty"`
	Context                        []byte       `protobuf:"bytes,12,opt,name=context,proto3" json:"context,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptorMessage, []int{0} }

func init() {
	proto.RegisterType((*Message)(nil), "raftpb.Message")
}
func (m *Message) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Message) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Type != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintMessage(dAtA, i, uint64(m.Type))
	}
	if m.From != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintMessage(dAtA, i, uint64(m.From))
	}
	if m.To != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintMessage(dAtA, i, uint64(m.To))
	}
	if m.SenderCurrentCommittedIndex != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintMessage(dAtA, i, uint64(m.SenderCurrentCommittedIndex))
	}
	if m.SenderCurrentTerm != 0 {
		dAtA[i] = 0x28
		i++
		i = encodeVarintMessage(dAtA, i, uint64(m.SenderCurrentTerm))
	}
	if m.LogIndex != 0 {
		dAtA[i] = 0x30
		i++
		i = encodeVarintMessage(dAtA, i, uint64(m.LogIndex))
	}
	if m.LogTerm != 0 {
		dAtA[i] = 0x38
		i++
		i = encodeVarintMessage(dAtA, i, uint64(m.LogTerm))
	}
	if len(m.Entries) > 0 {
		for _, msg := range m.Entries {
			dAtA[i] = 0x42
			i++
			i = encodeVarintMessage(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	dAtA[i] = 0x4a
	i++
	i = encodeVarintMessage(dAtA, i, uint64(m.Snapshot.Size()))
	n1, err := m.Snapshot.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n1
	if m.Reject {
		dAtA[i] = 0x50
		i++
		if m.Reject {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if m.RejectHintFollowerLogLastIndex != 0 {
		dAtA[i] = 0x58
		i++
		i = encodeVarintMessage(dAtA, i, uint64(m.RejectHintFollowerLogLastIndex))
	}
	if len(m.Context) > 0 {
		dAtA[i] = 0x62
		i++
		i = encodeVarintMessage(dAtA, i, uint64(len(m.Context)))
		i += copy(dAtA[i:], m.Context)
	}
	return i, nil
}

func encodeFixed64Message(dAtA []byte, offset int, v uint64) int {
	dAtA[offset] = uint8(v)
	dAtA[offset+1] = uint8(v >> 8)
	dAtA[offset+2] = uint8(v >> 16)
	dAtA[offset+3] = uint8(v >> 24)
	dAtA[offset+4] = uint8(v >> 32)
	dAtA[offset+5] = uint8(v >> 40)
	dAtA[offset+6] = uint8(v >> 48)
	dAtA[offset+7] = uint8(v >> 56)
	return offset + 8
}
func encodeFixed32Message(dAtA []byte, offset int, v uint32) int {
	dAtA[offset] = uint8(v)
	dAtA[offset+1] = uint8(v >> 8)
	dAtA[offset+2] = uint8(v >> 16)
	dAtA[offset+3] = uint8(v >> 24)
	return offset + 4
}
func encodeVarintMessage(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *Message) Size() (n int) {
	var l int
	_ = l
	if m.Type != 0 {
		n += 1 + sovMessage(uint64(m.Type))
	}
	if m.From != 0 {
		n += 1 + sovMessage(uint64(m.From))
	}
	if m.To != 0 {
		n += 1 + sovMessage(uint64(m.To))
	}
	if m.SenderCurrentCommittedIndex != 0 {
		n += 1 + sovMessage(uint64(m.SenderCurrentCommittedIndex))
	}
	if m.SenderCurrentTerm != 0 {
		n += 1 + sovMessage(uint64(m.SenderCurrentTerm))
	}
	if m.LogIndex != 0 {
		n += 1 + sovMessage(uint64(m.LogIndex))
	}
	if m.LogTerm != 0 {
		n += 1 + sovMessage(uint64(m.LogTerm))
	}
	if len(m.Entries) > 0 {
		for _, e := range m.Entries {
			l = e.Size()
			n += 1 + l + sovMessage(uint64(l))
		}
	}
	l = m.Snapshot.Size()
	n += 1 + l + sovMessage(uint64(l))
	if m.Reject {
		n += 2
	}
	if m.RejectHintFollowerLogLastIndex != 0 {
		n += 1 + sovMessage(uint64(m.RejectHintFollowerLogLastIndex))
	}
	l = len(m.Context)
	if l > 0 {
		n += 1 + l + sovMessage(uint64(l))
	}
	return n
}

func sovMessage(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozMessage(x uint64) (n int) {
	return sovMessage(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Message) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMessage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Message: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Message: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Type |= (MESSAGE_TYPE(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field From", wireType)
			}
			m.From = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.From |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field To", wireType)
			}
			m.To = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.To |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SenderCurrentCommittedIndex", wireType)
			}
			m.SenderCurrentCommittedIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SenderCurrentCommittedIndex |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SenderCurrentTerm", wireType)
			}
			m.SenderCurrentTerm = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SenderCurrentTerm |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LogIndex", wireType)
			}
			m.LogIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LogIndex |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LogTerm", wireType)
			}
			m.LogTerm = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LogTerm |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Entries", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Entries = append(m.Entries, Entry{})
			if err := m.Entries[len(m.Entries)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Snapshot", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Snapshot.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reject", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Reject = bool(v != 0)
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RejectHintFollowerLogLastIndex", wireType)
			}
			m.RejectHintFollowerLogLastIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RejectHintFollowerLogLastIndex |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Context", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Context = append(m.Context[:0], dAtA[iNdEx:postIndex]...)
			if m.Context == nil {
				m.Context = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMessage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMessage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMessage(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMessage
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthMessage
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowMessage
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipMessage(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthMessage = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMessage   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("raft/raftpb/message.proto", fileDescriptorMessage) }

var fileDescriptorMessage = []byte{
	// 406 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x91, 0xc1, 0x6e, 0x94, 0x40,
	0x1c, 0xc6, 0x77, 0x76, 0x11, 0x70, 0xb6, 0x36, 0x3a, 0x69, 0x74, 0xc4, 0x04, 0x89, 0x27, 0x0e,
	0x16, 0x12, 0x7c, 0x01, 0x6d, 0xc3, 0xaa, 0x09, 0x4d, 0x0c, 0x70, 0xf1, 0xd4, 0xc0, 0xee, 0x94,
	0x62, 0xca, 0xfc, 0xc9, 0x30, 0x1b, 0xcb, 0x9b, 0xf8, 0x48, 0x7b, 0xf4, 0xec, 0xc1, 0xe8, 0xfa,
	0x22, 0x66, 0x67, 0x60, 0xb3, 0x46, 0x63, 0x2f, 0xe4, 0xff, 0x7d, 0xdf, 0xef, 0x9b, 0xe1, 0x0f,
	0xf8, 0xa9, 0x28, 0xae, 0x64, 0xb8, 0x7b, 0xb4, 0x65, 0xd8, 0xb0, 0xae, 0x2b, 0x2a, 0x16, 0xb4,
	0x02, 0x24, 0x10, 0x53, 0xbb, 0xce, 0x69, 0x55, 0xcb, 0xeb, 0x75, 0x19, 0x2c, 0xa1, 0x09, 0x2b,
	0xa8, 0x20, 0x54, 0x71, 0xb9, 0xbe, 0x52, 0x4a, 0x09, 0x35, 0xe9, 0x9a, 0xf3, 0xe4, 0xf0, 0x44,
	0xc6, 0xa5, 0xe8, 0x87, 0xc0, 0xfd, 0xc7, 0x55, 0x97, 0xb2, 0x6f, 0x87, 0xfb, 0x1c, 0xe7, 0x30,
	0xef, 0x78, 0xd1, 0x76, 0xd7, 0x20, 0x75, 0xf6, 0xe2, 0xdb, 0x0c, 0x5b, 0x17, 0xba, 0x42, 0x7c,
	0x6c, 0xe4, 0x7d, 0xcb, 0x28, 0xf2, 0x90, 0x7f, 0x1c, 0x9d, 0x04, 0xba, 0x11, 0x5c, 0xc4, 0x59,
	0xf6, 0xe6, 0x6d, 0x7c, 0x99, 0x7f, 0xfc, 0x10, 0xa7, 0x8a, 0x20, 0x04, 0x1b, 0x0b, 0x01, 0x0d,
	0x9d, 0x7a, 0xc8, 0x37, 0x52, 0x35, 0x93, 0x63, 0x3c, 0xcd, 0x81, 0xce, 0x94, 0x33, 0xcd, 0x81,
	0xbc, 0xc6, 0xcf, 0x32, 0xc6, 0x57, 0x4c, 0x9c, 0xaf, 0x85, 0x60, 0x5c, 0x9e, 0x43, 0xd3, 0xd4,
	0x52, 0xb2, 0xd5, 0x7b, 0xbe, 0x62, 0xb7, 0xd4, 0x50, 0xe0, 0xff, 0x10, 0xf2, 0x12, 0x3f, 0xfa,
	0x23, 0xce, 0x99, 0x68, 0xe8, 0x3d, 0xd5, 0xfb, 0x3b, 0x20, 0x0e, 0xb6, 0x13, 0xa8, 0xf4, 0xe1,
	0xa6, 0x82, 0xf6, 0x9a, 0x50, 0x6c, 0x25, 0x50, 0xa9, 0xbe, 0xa5, 0xa2, 0x51, 0x92, 0x53, 0x6c,
	0xc5, 0x5c, 0x8a, 0x9a, 0x75, 0xd4, 0xf6, 0x66, 0xfe, 0x3c, 0x7a, 0x30, 0xae, 0xbd, 0xb3, 0xfb,
	0x33, 0x63, 0xf3, 0xfd, 0xf9, 0x24, 0x1d, 0x19, 0x12, 0x61, 0x3b, 0x1b, 0x3e, 0x20, 0xbd, 0xef,
	0x21, 0x7f, 0x1e, 0x3d, 0x1c, 0xf9, 0xd1, 0x1f, 0x2a, 0x7b, 0x8e, 0x3c, 0xc6, 0x66, 0xca, 0x3e,
	0xb1, 0xa5, 0xa4, 0xd8, 0x43, 0xbe, 0x9d, 0x0e, 0x8a, 0x2c, 0xb0, 0xab, 0xa7, 0x77, 0x35, 0x97,
	0x0b, 0xb8, 0xb9, 0x81, 0xcf, 0x4c, 0x24, 0x50, 0x25, 0x45, 0x27, 0xf5, 0x1a, 0x73, 0xf5, 0xae,
	0x77, 0x50, 0xbb, 0xe5, 0x96, 0xc0, 0x25, 0xbb, 0x95, 0xf4, 0xc8, 0x43, 0xfe, 0x51, 0x3a, 0xca,
	0xb3, 0x93, 0xcd, 0x4f, 0x77, 0xb2, 0xd9, 0xba, 0xe8, 0xeb, 0xd6, 0x45, 0x3f, 0xb6, 0x2e, 0xfa,
	0xf2, 0xcb, 0x9d, 0x94, 0xa6, 0xfa, 0xf3, 0xaf, 0x7e, 0x07, 0x00, 0x00, 0xff, 0xff, 0xdc, 0x77,
	0x84, 0x33, 0xa2, 0x02, 0x00, 0x00,
}
