// Code generated by protoc-gen-gogo.
// source: raft/raftpb/other_types.proto
// DO NOT EDIT!

/*
	Package raftpb is a generated protocol buffer package.

	It is generated from these files:
		raft/raftpb/other_types.proto
		raft/raftpb/raftpb.proto

	It has these top-level messages:
		Entry
		ConfigState
		SnapshotMetadata
		Snapshot
		HardState
		ConfigChange
		Message
*/
package raftpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

// NODE_STATE represents the state of a node in a cluster.
type NODE_STATE int32

const (
	NODE_STATE_FOLLOWER  NODE_STATE = 0
	NODE_STATE_CANDIDATE NODE_STATE = 1
	NODE_STATE_LEADER    NODE_STATE = 2
)

var NODE_STATE_name = map[int32]string{
	0: "FOLLOWER",
	1: "CANDIDATE",
	2: "LEADER",
}
var NODE_STATE_value = map[string]int32{
	"FOLLOWER":  0,
	"CANDIDATE": 1,
	"LEADER":    2,
}

func (x NODE_STATE) String() string {
	return proto.EnumName(NODE_STATE_name, int32(x))
}
func (NODE_STATE) EnumDescriptor() ([]byte, []int) { return fileDescriptorOtherTypes, []int{0} }

// PROGRESS_STATE represents the state of Progress.
// Progress is leader's view of its followers' progress.
// Leader maintains progresses of all followers, and
// replicates entries to the followers based on their progresses.
// Progress has 'MatchIndex' and 'NextIndex'. 'MatchIndex' is the
// highest known matched index of follower entries. If unknown,
// it is set to 0. Then leader replicates entries from 'NextIndex'
// to its last one.
type PROGRESS_STATE int32

const (
	// When a follower is in PROBE state, leader sends at most one message
	// for each heartbeat interval. This is to probe the actual progress of
	// the follower.
	PROGRESS_STATE_PROBE PROGRESS_STATE = 0
	// When a follower is in REPLICATE state, leader replicates messages
	// by optimistically increasing 'NextIndex' to latest. This is an
	// optimized state for fast log replication. If it fails, leader sets
	// it back to PROBE.
	// The maximum number of entries per message and the maximum number of
	// inflight messages are configurable.
	PROGRESS_STATE_REPLICATE PROGRESS_STATE = 1
	// Leader changes follower's state from PROBE to SNAPSHOT
	// when the follower has fallen too far behind the leader,
	// and sends snapshot to the follower. Then leader must wait
	// until the success. After snapshot is applied, leader sets
	// it back to PROBE.
	PROGRESS_STATE_SNAPSHOT PROGRESS_STATE = 2
)

var PROGRESS_STATE_name = map[int32]string{
	0: "PROBE",
	1: "REPLICATE",
	2: "SNAPSHOT",
}
var PROGRESS_STATE_value = map[string]int32{
	"PROBE":     0,
	"REPLICATE": 1,
	"SNAPSHOT":  2,
}

func (x PROGRESS_STATE) String() string {
	return proto.EnumName(PROGRESS_STATE_name, int32(x))
}
func (PROGRESS_STATE) EnumDescriptor() ([]byte, []int) { return fileDescriptorOtherTypes, []int{1} }

// SNAPSHOT_STATE represents the state of snapshot.
type SNAPSHOT_STATE int32

const (
	SNAPSHOT_STATE_FINISHED SNAPSHOT_STATE = 0
	SNAPSHOT_STATE_FAILED   SNAPSHOT_STATE = 1
)

var SNAPSHOT_STATE_name = map[int32]string{
	0: "FINISHED",
	1: "FAILED",
}
var SNAPSHOT_STATE_value = map[string]int32{
	"FINISHED": 0,
	"FAILED":   1,
}

func (x SNAPSHOT_STATE) String() string {
	return proto.EnumName(SNAPSHOT_STATE_name, int32(x))
}
func (SNAPSHOT_STATE) EnumDescriptor() ([]byte, []int) { return fileDescriptorOtherTypes, []int{2} }

func init() {
	proto.RegisterEnum("raftpb.NODE_STATE", NODE_STATE_name, NODE_STATE_value)
	proto.RegisterEnum("raftpb.PROGRESS_STATE", PROGRESS_STATE_name, PROGRESS_STATE_value)
	proto.RegisterEnum("raftpb.SNAPSHOT_STATE", SNAPSHOT_STATE_name, SNAPSHOT_STATE_value)
}

var fileDescriptorOtherTypes = []byte{
	// 242 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x92, 0x2d, 0x4a, 0x4c, 0x2b,
	0xd1, 0x07, 0x11, 0x05, 0x49, 0xfa, 0xf9, 0x25, 0x19, 0xa9, 0x45, 0xf1, 0x25, 0x95, 0x05, 0xa9,
	0xc5, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0x6c, 0x10, 0x19, 0x29, 0xdd, 0xf4, 0xcc, 0x92,
	0x8c, 0xd2, 0x24, 0xbd, 0xe4, 0xfc, 0x5c, 0xfd, 0xf4, 0xfc, 0xf4, 0x7c, 0x7d, 0xb0, 0x74, 0x52,
	0x69, 0x1a, 0x98, 0x07, 0xe6, 0x80, 0x59, 0x10, 0x6d, 0x5a, 0xa6, 0x5c, 0x5c, 0x7e, 0xfe, 0x2e,
	0xae, 0xf1, 0xc1, 0x21, 0x8e, 0x21, 0xae, 0x42, 0x3c, 0x5c, 0x1c, 0x6e, 0xfe, 0x3e, 0x3e, 0xfe,
	0xe1, 0xae, 0x41, 0x02, 0x0c, 0x42, 0xbc, 0x5c, 0x9c, 0xce, 0x8e, 0x7e, 0x2e, 0x9e, 0x2e, 0x8e,
	0x21, 0xae, 0x02, 0x8c, 0x42, 0x5c, 0x5c, 0x6c, 0x3e, 0xae, 0x8e, 0x2e, 0xae, 0x41, 0x02, 0x4c,
	0x5a, 0x16, 0x5c, 0x7c, 0x01, 0x41, 0xfe, 0xee, 0x41, 0xae, 0xc1, 0xc1, 0x50, 0xad, 0x9c, 0x5c,
	0xac, 0x01, 0x41, 0xfe, 0x4e, 0xae, 0x10, 0x7d, 0x41, 0xae, 0x01, 0x3e, 0x9e, 0xce, 0x10, 0x7d,
	0x3c, 0x5c, 0x1c, 0xc1, 0x7e, 0x8e, 0x01, 0xc1, 0x1e, 0xfe, 0x21, 0x02, 0x4c, 0x5a, 0x5a, 0x5c,
	0x7c, 0x30, 0x1e, 0x92, 0xa5, 0x9e, 0x7e, 0x9e, 0xc1, 0x1e, 0xae, 0x2e, 0x02, 0x0c, 0x20, 0x5b,
	0xdc, 0x1c, 0x3d, 0x7d, 0x5c, 0x5d, 0x04, 0x18, 0x9d, 0x44, 0x4e, 0x3c, 0x94, 0x63, 0x38, 0xf1,
	0x48, 0x8e, 0xf1, 0xc2, 0x23, 0x39, 0xc6, 0x07, 0x8f, 0xe4, 0x18, 0x67, 0x3c, 0x96, 0x63, 0x48,
	0x62, 0x03, 0xbb, 0xdc, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x0b, 0xf2, 0x36, 0x72, 0x11, 0x01,
	0x00, 0x00,
}
